server:
  port: ${SERVER_PORT:3001}

spring:
  application:
    name: AUTH-SERVER
  jpa:
    database: mysql
    open-in-view: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        use_sql_comments: true
        show_sql: true
        format_sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bookstore_db?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: PaSSworD
  main:
    allow-bean-definition-overriding: true


eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:localhost:8761}/eureka/
    registerWithEureka: true
    fetch-registry: true #eureka discovery is enabled in this profile
  instance:
    prefer-ip-address: false

com:
  sp:
    spring:
      jwt:
        secret-key: 093617ebfa4b9af9700db274ac204ffa34195494d97b9c26c23ad561de817926
      security:
        client-id: client
        response-type: code
        code-challenge-method: S256
        redirect-uri: https://www.github.com/hardikSinghBehl, http://127.0.0.1:3000/authorized,
          https://www.linkedin.com/in/hardiksinghbehl
        refresh:
          grant-type: refresh_token
        code-expiration-minutes: '5'
        grant-type: authorization_code
