server:
  port: ${SERVER_PORT:9191}

spring:
  application:
    name: API-GATEWAY-SERVICE
  cloud:
    gateway:
      routes:
        - id: catalog-service
          uri: lb://CATALOG-SERVICE
          predicates:
            - Path=/api/catalog/**
          filters:
            - StripPrefix=2

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:localhost:8761}/eureka/
    registerWithEureka: true
    fetch-registry: true #eureka discovery is enabled in this profile
  instance:
    prefer-ip-address: false