server:
  port: ${SERVER_PORT:9191}

spring:
  application:
    name: API-GATEWAY-SERVICE
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/api/order/**
          filters:
            - StripPrefix=2
        - id: catalog-service
          uri: lb://CATALOG-SERVICE
          predicates:
            - Path=/api/catalog/**
          filters:
            - StripPrefix=2
        - id: account-service
          uri: lb://ACCOUNT-SERVICE
          predicates:
            - Path=/api/account/**
          filters:
            - StripPrefix=2
#        - id: auth-server
#          uri: lb://AUTH-SERVER
#          predicates:
#            - Path=/api/auth/**
#          filters:
#            - StripPrefix=2
        - id: resource-server
          uri: lb://RESOURCE-SERVER
          predicates:
            - Path=/api/resource/**
          filters:
            - StripPrefix=2

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:localhost:8761}/eureka/
    registerWithEureka: true
    fetch-registry: true #eureka discovery is enabled in this profile
  instance:
    prefer-ip-address: false